name: ACE Model CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Weekly tests (Monday at 00:00 UTC)
    - cron: '0 0 * * 1'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v --cov=src --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
    
    - name: Run symbolic notebooks
      run: |
        python scripts/run_notebooks.py
    
    - name: Generate figures (test run)
      run: |
        python scripts/generate_figure1.py
        python scripts/generate_figure2.py
      continue-on-error: true  # Allow failure if display not available
    
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.10'
    
    - name: Install linters
      run: |
        pip install flake8 black isort mypy
    
    - name: Check code formatting with black
      run: |
        black --check src/ tests/ scripts/
    
    - name: Check imports with isort
      run: |
        isort --check-only src/ tests/ scripts/
    
    - name: Lint with flake8
      run: |
        flake8 src/ tests/ scripts/ --count --max-complexity=10 --statistics
    
    - name: Type check with mypy
      run: |
        mypy src/ --ignore-missing-imports
    
  documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pdoc3
    
    - name: Generate API documentation
      run: |
        pdoc --html --output-dir docs/ src/
    
    - name: Verify README links
      run: |
        # Check for broken links in documentation
        python -c "
        import os
        readme_path = 'README.md'
        if os.path.exists(readme_path):
            with open(readme_path, 'r') as f:
                content = f.read()
                # Check for common patterns of broken links
                import re
                links = re.findall(r'\[.*?\]\((.*?)\)', content)
                print(f'Found {len(links)} links in README')
        "
    
    - name: Archive documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/
    
  release:
    needs: [test, lint, documentation]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Test package installation
      run: |
        pip install dist/*.whl
        python -c "import ace_model; print('Package installed successfully')"
    
    - name: Create release archive
      run: |
        # Create a release archive with all necessary files
        tar -czf ACE-reproducibility-${{ github.ref_name }}.tar.gz \
          src/ \
          notebooks/ \
          scripts/ \
          tests/ \
          docs/ \
          requirements.txt \
          LICENSE \
          README.md \
          CITATION.cff
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ACE-reproducibility-${{ github.ref_name }}.tar.gz
          dist/*.whl
          dist/*.tar.gz
    
    - name: Publish to Test PyPI
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}